name: Build and Test
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [stable, oldstable]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build and Test
        run: ./scripts/ci.sh
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Build and Test
        run: .\scripts\ci.ps1
        if: ${{ matrix.os == 'windows-latest' }}
